name: 'Semantic branch version'
author: 'Koen Eijkemans'
description: 'Github action that grabs a version from the branch name'
outputs:
  branchname:
    description: name of the branch
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'check'
  color: 'green'